apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: my-pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeClaimPolicy: Retain
  nfs:
    server: 192.168.10.120
    path: "/mnt/nfs"
  storageClassName: giropops
