apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-example
  name: external-example
spec:
  externalName: external.example.com
  selector:
    app: external-example
  type: ExternalName
