apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
