apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-nodeport
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 32000
  selector:
    app: nginx
  type: NodePort
