apiVersion: v1
kind: Pod
metadata:
  name: nginx-tls
  namespace: dk8s
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: nginx-conf-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: nginx-tls
      mountPath: /etc/nginx/tls
  volumes:
  - name: nginx-conf-volume
    configMap:
      name: nginx-config
  - name: nginx-tls
    secret:
      secretName: my-service-tls-secret
      items:
      - key: tls.crt
        path: cert.crt
      - key: tls.key
        path: private-key.pem
