apiVersion: v1
kind: Pod
metadata:
  name: giropops
  namespace: dk8s
  labels:
    run: giropops
spec:
  containers:
  - name: girus
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.2"
      requests:
        memory: "10Mi"
        cpu: "0.1"
