apiVersion: v1
kind: Pod
metadata:
  name: giropops
  namespace: dk8s
  labels: 
    run: giropops
spec:
  containers:
  - name: girus
    image: nginx
    ports:
    - containerPort: 80
  - name: strigus
    image: alpine
    args:
    - sleep
    - "600"
